services:
  local-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: atma17-dev-environment
    container_name: atma17-dev-container
    shm_size: 120g
    ports:
      - "127.0.0.1:9896:9896"
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    volumes:
      - .:/workspace/working
      - ${HOME}/.ssh:/home/docker/.ssh
